# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('cdescription', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttime', models.DateTimeField()),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='Logon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'logon',
            },
        ),
        migrations.CreateModel(
            name='Projectlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'projectLike',
            },
        ),
        migrations.CreateModel(
            name='Projectpledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pledgetime', models.DateTimeField()),
                ('pledgestatus', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'projectPledge',
            },
        ),
        migrations.CreateModel(
            name='Projectpropose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pdescription', models.CharField(blank=True, max_length=200, null=True)),
                ('likecount', models.IntegerField(blank=True, null=True)),
                ('backcount', models.IntegerField(blank=True, null=True)),
                ('minbudget', models.DecimalField(decimal_places=0, max_digits=10)),
                ('maxbudget', models.DecimalField(decimal_places=0, max_digits=10)),
                ('amountpledged', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pstarttime', models.DateTimeField()),
                ('plancompletetime', models.DateTimeField()),
                ('actualcompletetime', models.DateTimeField(blank=True, null=True)),
                ('pstatus', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Category')),
            ],
            options={
                'db_table': 'projectPropose',
            },
        ),
        migrations.CreateModel(
            name='Projectrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratetime', models.DateTimeField()),
                ('rate', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose')),
            ],
            options={
                'db_table': 'projectRate',
            },
        ),
        migrations.CreateModel(
            name='Projectsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose')),
            ],
            options={
                'db_table': 'projectSample',
            },
        ),
        migrations.CreateModel(
            name='Projectupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatenumber', models.IntegerField()),
                ('postdate', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose')),
            ],
            options={
                'db_table': 'projectUpdate',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('hometown', models.CharField(blank=True, max_length=20, null=True)),
                ('interests', models.CharField(blank=True, max_length=20, null=True)),
                ('registertime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Usercreditcardinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditno', models.CharField(max_length=50)),
                ('validdate', models.DateField()),
                ('securitycode', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User')),
            ],
            options={
                'db_table': 'userCreditcardInfo',
            },
        ),
        migrations.AddField(
            model_name='projectrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='projectpropose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='projectpledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose'),
        ),
        migrations.AddField(
            model_name='projectpledge',
            name='uciid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Usercreditcardinfo'),
        ),
        migrations.AddField(
            model_name='projectpledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose'),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='logon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kickstar.Projectpropose'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyusername',
            field=models.ForeignKey(blank=True, db_column='replyusername', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_requests_created', to='kickstar.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='kickstar.User'),
        ),
        migrations.AlterUniqueTogether(
            name='usercreditcardinfo',
            unique_together=set([('username', 'creditno')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectupdate',
            unique_together=set([('project', 'updatenumber')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectsample',
            unique_together=set([('project', 'url')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectrate',
            unique_together=set([('project', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectpledge',
            unique_together=set([('project', 'user', 'pledgetime')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectlike',
            unique_together=set([('project', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('followee', 'follower')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('project', 'commenttime', 'username')]),
        ),
    ]
