# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreditcardinfo',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='logon',
            unique_together=set([('user',)]),
        ),
        migrations.AlterUniqueTogether(
            name='usercreditcardinfo',
            unique_together=set([('user', 'creditno')]),
        ),
    ]
