# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0002_auto_20170429_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpropose',
            name='pbackgroundpic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
