# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 16:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0003_projectpropose_pbackgroundpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpropose',
            name='pcontentdetail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
