# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0004_projectpropose_pcontentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditcardinfo',
            name='creditname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
