# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0006_auto_20170503_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpropose',
            name='pbackgroundpic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
