# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 18:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0007_auto_20170503_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpropose',
            name='pcontentdetail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
