# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0008_auto_20170503_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpropose',
            name='pmovieurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projectpropose',
            name='pbackgroundpic',
            field=models.ImageField(blank=True, null=True, upload_to='kickstar/images/'),
        ),
    ]
