# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0011_auto_20170504_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='updatenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectupdate',
            unique_together=set([('project', 'updatenumber')]),
        ),
    ]
