# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0012_auto_20170504_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='updatenumber',
        ),
        migrations.AlterUniqueTogether(
            name='projectupdate',
            unique_together=set([('project', 'postdate')]),
        ),
    ]
