# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0013_auto_20170504_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='updatenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
