# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickstar', '0014_projectupdate_updatenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='updatenumber',
        ),
    ]
